### ISSUE TITLE
add Encode Educate Series to Learning Page

### ISSUE THREAD

**Issue by humanman** [near-horizon/horizon#22]

**Comment by humanman** [comment]
@petarvujovic98 I added sourcecode of supporting widgets to the project - Card.Partner.jsx & List.Partner.jsx
FYI I updated the paths to the new widgets with `${ownerId}` although NH hasn't forked them yet.

**Comment by petarvujovic98** [comment]
@humanman I've left comments on #23 regarding how to properly name and place these files, after which I will deploy them on-chain

**Comment by humanman** [comment]
@petarvujovic98 I made requested changes. Let me know if there is more to do. thanks
